baseURL = "https://joecatholic.netlify.com"
languageCode = "en-us"
title = "Joe Catholic"
theme = "mediumish-gohugo-theme"
summaryLength = 25
copyright = "2020 Father Christopher J. Decker - All rights reserved"
enableEmoji = true
publishDir = "docs"

[params]
  logo = "/images/joe-catholic-header-title.png"
  description ="Discipleship is an Adventure"
  #mailchimp = "you can provide a mailchimp-link here"

[params.author]
  name = "John Doe"
  thumbnail = "/images/author.png"
  description = "Creator of this blog."

[params.index]
  picture = "/images/author.png"
  title = "John Doe"
  subtitle = "I'm a unique placeholder. Working here and there!"
  mdtext = '''
Currently trying to get this blog running, still don't know what the blog will be about!\
**This textblock is a demonstration of the mdtext-param.**\
### This is a markdown heading
'''
  alertbar = false

[params.social]
  twitter = "joecatholic"
  instagram = "digitalcatholic"

## Main Menu
[[menu.main]]
    name = "Comics"
    weight = 100
    identifier = "comics"
    url = "/comics"
[[menu.main]]
    name = "About"
    identifier = "about"
    weight = 200
    url = "/static/about"
[[menu.main]]
        name = "Permissions"
        identifier = "permissions"
        weight = 300
        url = "/static/permissions"
